#!/usr/bin/env node
/**
 * FDD Protect Hook - Auto-generated by fdd-cli
 * DO NOT EDIT MANUALLY - regenerated on each fdd add
 *
 * Intercepts Write/Edit tool calls and blocks/warns based on
 * protect rules defined in .fdd/pits/
 */

const { minimatch } = require("minimatch");
const fs = require("fs");
const path = require("path");

const PROTECT_RULES = [
  {
    "pitfallId": "PIT-000",
    "pitfallTitle": "[示例] 保护 pitfall 文件不被 AI 直接写入",
    "triggerIndex": 0,
    "paths": [
      ".fdd/pits/**"
    ],
    "exclude": [
      "_template.md",
      "pit-000-*.md"
    ],
    "permissions": {
      "create": "deny",
      "update": "allow",
      "delete": "allow"
    },
    "message": "请使用 fdd add --json 命令创建 pitfall，而不是直接写入文件"
  }
];

let inputData = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => { inputData += chunk; });
process.stdin.on("end", () => {
  try {
    processToolCall(JSON.parse(inputData));
  } catch (error) {
    process.exit(0);
  }
});

function processToolCall(input) {
  const { tool_input } = input;
  const cwd = process.cwd();

  const filePath = tool_input?.file_path || tool_input?.path || "";
  if (!filePath) process.exit(0);

  const relativePath = filePath.startsWith("/")
    ? path.relative(cwd, filePath)
    : filePath;

  const isCreate = !fs.existsSync(path.resolve(cwd, relativePath));
  const operation = isCreate ? "create" : "update";

  for (const rule of PROTECT_RULES) {
    const matchesPath = rule.paths.some(pattern =>
      minimatch(relativePath, pattern) || minimatch(filePath, pattern)
    );
    if (!matchesPath) continue;

    const isExcluded = rule.exclude.some(pattern =>
      minimatch(relativePath, pattern) || minimatch(filePath, pattern)
    );
    if (isExcluded) continue;

    const permission = rule.permissions[operation];
    if (permission === "deny") {
      const message = rule.message ||
        `[FDD] File "${relativePath}" is protected by ${rule.pitfallId}: ${rule.pitfallTitle}`;
      console.error(`\n🚫 ${message}\n`);
      console.error(`   Operation: ${operation}`);
      console.error(`   Pitfall: ${rule.pitfallId}\n`);
      process.exit(2);
    }
  }

  process.exit(0);
}
