/**
 * FDD Context Pre Hook Generator
 * Alerts user via systemMessage when AI edits files matching ai-context rules
 *
 * Due to Claude Code limitations, PreToolUse cannot inject context directly to AI.
 * Instead, we use systemMessage to alert the user, who can then manually intervene.
 */

import { existsSync } from "node:fs";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Pitfall } from "../../types/index.js";
import {
	type AiContextRule,
	extractAiContextRules,
} from "../trigger/ai-context.js";
import { HOOKS_DIR, HOOK_FILES, type SyncResult } from "./types.js";

/**
 * Sync context-pre hooks (PreToolUse)
 */
export async function syncContextPreHook(
	cwd: string,
	pitfalls: Pitfall[],
): Promise<SyncResult> {
	const hooksDir = join(cwd, HOOKS_DIR);
	const hookPath = join(hooksDir, HOOK_FILES.contextPre);

	const rules = extractAiContextRules(pitfalls);

	if (rules.length === 0) {
		if (existsSync(hookPath)) {
			await unlink(hookPath);
		}
		return { hooksPath: hookPath, rulesCount: 0, generated: false };
	}

	await mkdir(hooksDir, { recursive: true });
	await writeFile(hookPath, generateScript(rules), "utf-8");

	return { hooksPath: hookPath, rulesCount: rules.length, generated: true };
}

function generateScript(rules: AiContextRule[]): string {
	const rulesJson = JSON.stringify(rules, null, 2);

	return `#!/usr/bin/env node
/**
 * FDD Context Pre Hook - Auto-generated by fdd-cli
 * DO NOT EDIT MANUALLY - regenerated on each fdd add
 *
 * Intercepts PreToolUse (Write/Edit/MultiEdit) and alerts user via systemMessage
 * when AI edits files matching ai-context rules.
 *
 * Due to Claude Code limitations, PreToolUse cannot inject context directly to AI.
 * Instead, we use systemMessage to alert the user, who can then manually intervene.
 */

const { minimatch } = require("minimatch");

const CONTEXT_RULES = ${rulesJson};

let inputData = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => { inputData += chunk; });
process.stdin.on("end", () => {
  try {
    processToolUse(JSON.parse(inputData));
  } catch (error) {
    process.exit(0);
  }
});

function processToolUse(input) {
  const toolInput = input.tool_input || {};
  const filePath = toolInput.file_path || "";

  if (!filePath) process.exit(0);

  // Normalize path
  let normalizedPath = filePath;
  if (normalizedPath.startsWith("./")) {
    normalizedPath = normalizedPath.slice(2);
  }
  // Extract relative path from absolute path
  const cwdMatch = normalizedPath.match(/\\/(?:src|lib|app|components|routes|db)\\//);
  if (cwdMatch) {
    normalizedPath = normalizedPath.slice(normalizedPath.indexOf(cwdMatch[0]) + 1);
  }

  const matchedContexts = [];

  for (const rule of CONTEXT_RULES) {
    let matched = false;

    for (const pattern of rule.whenTouching) {
      if (minimatch(normalizedPath, pattern) || normalizedPath.includes(pattern.replace(/\\*\\*/g, "").replace(/\\*/g, ""))) {
        const isExcluded = rule.exclude.some(excl => minimatch(normalizedPath, excl));
        if (!isExcluded) {
          matched = true;
          break;
        }
      }
    }

    if (matched) {
      matchedContexts.push(rule);
    }
  }

  if (matchedContexts.length > 0) {
    // Build systemMessage to alert user
    const warnings = matchedContexts.map(ctx =>
      \`\${ctx.pitfallId}: \${ctx.pitfallTitle}\`
    ).join("\\n");

    const docPaths = matchedContexts.map(ctx =>
      \`@.fdd/pitfalls/\${ctx.pitfallFilename}\`
    ).join(" ");

    const systemMessage = \`⚠️ [FDD] AI 正在编辑危险区域文件: \${normalizedPath}

相关陷阱记录:
\${warnings}

📋 由于 Claude Code 限制，AI 可能不知道这些陷阱。
如需确保安全，可以：
1. 按 Esc 打断当前操作
2. 复制以下内容发送给 AI：
   请先阅读 \${docPaths} 再继续编辑\`;

    // Output JSON with systemMessage at top level
    const output = {
      continue: true,
      systemMessage: systemMessage,
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "allow"
      }
    };

    console.log(JSON.stringify(output));
    console.error(" ");
  }

  process.exit(0);
}
`;
}
